export const customerData = [
    {
      id: 1,
      name: "Bobby Gilbert",
      theme: "primary",
      email: "bobby@softnio.com",
      phone: "+342 675-6578",
      company: "Softnio",
      cardType: "visa",
      cardNumber: "**** 1955",
      joined: "12 Dec 2021, 12:12 am",
      status: "Active",
    },
    {
      id: 2,
      name: "Olivia Poulsen",
      theme: "red",
      email: "olivia@apple.com",
      phone: "+782 332-8328",
      company: "Apple",
      cardType: "mastercard",
      cardNumber: "**** 7473",
      joined: "08 Dec 2021, 04:03 am",
      status: "Active",
    },
    {
      id: 3,
      name: "Heather Marshall",
      img: "/images/avatar/b-sm.jpg",
      theme: "primary",
      email: "marshall@reakitt.com",
      phone: "+342 545-5639",
      company: "Reakitt",
      cardType: "amex",
      cardNumber: "**** 4355",
      joined: "02 Dec 2021, 02:34 am",
      status: "Inactive",
    },
    {
      id: 4,
      name: "Benjamin Harris",
      theme: "indigo",
      email: "info@mediavest.com",
      phone: "+342 675-6578",
      company: "MediaVest",
      cardType: "visa",
      cardNumber: "**** 3472",
      joined: "29 Nov 2021, 03:19 am",
      status: "Active",
    },
    {
      id: 5,
      name: "Joshua Kennedy	",
      theme: "yellow",
      email: "joshua@softnio.com",
      phone: "+323 345-8676",
      company: "Softnio",
      cardType: "visa",
      cardNumber: "**** 9878",
      joined: "24 Nov 2021, 04:21 am",
      status: "Active",
    },
    {
      id: 6,
      name: "Justine Bauwens",
      img: "/images/avatar/c-sm.jpg",
      theme: "primary",
      email: "bauwens@kline.com",
      phone: "+657 879-3214",
      company: "Kline",
      cardType: "mastercard",
      cardNumber: "**** 7657",
      joined: "19 Nov 2021, 09:56 am",
      status: "Active",
    },
    {
      id: 7,
      name: "Ethan Hunter",
      theme: "purple",
      email: "ethan@bergerpaints.com",
      phone: "+435 675-2345	",
      company: "Berger Paints",
      cardType: "visa",
      cardNumber: "**** 5435",
      joined: "13 Nov 2021, 05:45 am",
      status: "Active",
    },
    {
      id: 8,
      name: "Justine Bauwens",
      theme: "primary",
      email: "justine@acstext.com",
      phone: "+978 546-2342",
      company: "ACS Textiles",
      cardType: "visa",
      cardNumber: "**** 6577",
      joined: "06 Nov 2021, 06:34 am",
      status: "Active",
    },
    {
      id: 9,
      name: "Summer Powell",
      img: "/images/avatar/d-sm.jpg",
      theme: "primary",
      email: "info@youngone.com",
      phone: "+435 433-8767",
      company: "Youngone",
      cardType: "amex",
      cardNumber: "**** 5432",
      joined: "27 Oct 2021, 01:43 am",
      status: "Suspended",
    },
    {
      id: 10,
      name: "Sofia Maier",
      theme: "black",
      email: "sofia@unilever.com",
      phone: "+432 435-1233",
      company: "Unilever",
      cardType: "visa",
      cardNumber: "**** 6786",
      joined: "18 Oct 2021, 07:37 am",
      status: "Active",
    },
]